# Generated by scripts/generate_configs.sh — DO NOT EDIT
# Shared pgBackRest configuration: mounted into the backup repository host
# AND every DB node. Node-side entries (repo1-host) are ignored by the repo
# host itself; pg1-* entries are ignored during archive-push.
[global]
allow-root=y
repo1-type=posix
repo1-path=/var/lib/pgbackrest
repo1-retention-full=__PG_BACKUP_RETENTION_FULL__
repo1-host-user=backup
process-max=4
log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest
spool-path=/var/spool/pgbackrest
start-fast=y
archive-timeout=60
__REPO_HOST_LINES__

__STANZAS__
